### PR TITLE
Longest active streak function made including flask endpoint

### PR DESCRIPTION
**Pull request by raghavTinker**
The longest active streak function is made, including a flask endpoint. The endpoint is: ```http://hostname/<username>/streak```
Example:
Screenshot 2021-11-20 at 1 31 10 AM

### CODE REVIEW

**Comment by raghavTinker** [comment]
Lazy Gap endpoint also made. The endpoint is: ```http://hostname/raghavtinker/lazygap```
Example:
image

**Comment by raghavTinker** [comment]
Improved the way the lazy gap is generated.

**Comment by raghavTinker** [comment]
a) Monthly distribution endpoint made: ```http://hostname/raghavtinker/trends/month```
b) Day wise distribution endpoint made: ```http://hostname/raghavtinker/trends/day```

Example:
a) Month wise:
image

b) Day wise:
image

**Comment by Samikmalhotra** [comment]
Closes #3

**Pull request merged**
